// Converts the CC0 source sounds in assets-src/audio/src to the MP3 files the
// game loads (assets/audio/<id>.mp3) and writes assets/LICENSES.md.
//
//   node scripts/build-audio.mjs
//
// Uses Blender's bundled FFmpeg (see assets-src/audio/convert.py), so no extra
// tools are needed. Each entry in assets-src/audio/sounds.json describes the
// source file, an optional trim (start / duration in seconds), volume, fade-out
// and the license information.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const srcDir = join(root, "assets-src", "audio");
const outDir = join(root, "assets", "audio");
const manifest = JSON.parse(readFileSync(join(srcDir, "sounds.json"), "utf8"));

function findBlender() {
  if (process.env.BLENDER_PATH) return process.env.BLENDER_PATH;
  if (process.platform === "win32") {
    const base = join(process.env.ProgramFiles ?? "C:/Program Files", "Blender Foundation");
    if (existsSync(base)) {
      for (const dir of readdirSync(base).sort().reverse()) {
        const exe = join(base, dir, "blender.exe");
        if (existsSync(exe)) return exe;
      }
    }
  } else if (process.platform === "darwin" && existsSync("/Applications/Blender.app/Contents/MacOS/Blender")) {
    return "/Applications/Blender.app/Contents/MacOS/Blender";
  }
  return "blender";
}

mkdirSync(outDir, { recursive: true });
const jobs = Object.entries(manifest.sounds).map(([id, s]) => {
  const src = join(srcDir, s.file);
  if (!existsSync(src)) throw new Error(`Missing source for "${id}": ${src}`);
  return {
    src,
    dst: join(outDir, `${id}.mp3`),
    start: s.start ?? 0,
    duration: s.duration ?? null,
    volume: s.volume ?? 1,
    fade_out: s.fadeOut ?? 0,
    bitrate: s.bitrate ?? (id === "music" ? 112 : 96),
    stereo: id === "music",
  };
});

const work = mkdtempSync(join(tmpdir(), "killthebird-audio-"));
const jobFile = join(work, "jobs.json");
writeFileSync(jobFile, JSON.stringify(jobs));
try {
  const log = execFileSync(
    findBlender(),
    ["--background", "--factory-startup", "--python", join(srcDir, "convert.py"), "--", jobFile],
    { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
  );
  for (const line of log.split(/\r?\n/)) if (line.startsWith("[audio]")) console.log(line);
} finally {
  rmSync(work, { recursive: true, force: true });
}

let total = 0;
for (const job of jobs) total += statSync(job.dst).size;
console.log(`Total: ${(total / 1024).toFixed(1)} KB in ${outDir}`);

// Credits file shipped with the package.
const rows = Object.entries(manifest.sounds).map(
  ([id, s]) => `| \`${id}.mp3\` | [${s.title}](${s.url}) | ${s.author} | ${s.license} |`,
);
writeFileSync(
  join(root, "assets", "LICENSES.md"),
  [
    "# Asset licenses",
    "",
    "## 3D models",
    "",
    "All models in `models/` are generated by the package's own Blender scripts",
    "(`assets-src/blender/`) and are released under the package's MIT license.",
    "",
    "## Audio",
    "",
    "All sounds are released into the public domain (CC0 1.0). Credit is not",
    "required but given here with thanks. Files were trimmed, level-adjusted and",
    "converted to MP3.",
    "",
    "| File | Source | Author | License |",
    "|---|---|---|---|",
    ...rows,
    "",
  ].join("\n"),
);
console.log("Wrote assets/LICENSES.md");
